name: Android

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'ubuntu-22.04'
            mobile: 'android'
            args: ' --apk true '

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install Rust stable (android)
        if: matrix.mobile == 'android'
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android,armv7-linux-androideabi,i686-linux-android,x86_64-linux-android

      - name: Set up JDK
        if: matrix.mobile == 'android'
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Android SDK
        if: matrix.mobile == 'android'
        uses: android-actions/setup-android@v3

      - name: Setup Android NDK
        if: matrix.mobile == 'android'
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r29
          link-to-sdk: true

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          workspaces: |
            ./src-tauri -> ./target

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04' || matrix.platform == 'ubuntu-24.04' || matrix.platform == 'ubuntu-24.04-arm'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev librsvg2-dev libxdo-dev libssl-dev  libayatana-appindicator3-dev   librsvg2-dev

      - name: init mobile project
        if: matrix.mobile != ''
        run: |
          npx @tauri-apps/cli ${{ matrix.mobile }} init

      - name: install frontend dependencies
        run: yarn install

      - name: install icon
        run: yarn icon

      - name: setup Android signing
        if: matrix.mobile == 'android'
        run: |
          cd src-tauri/gen/android
          echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" > keystore.properties
          echo "password=${{ secrets.ANDROID_KEY_PASSWORD }}" >> keystore.properties
          base64 -d <<< "${{ secrets.ANDROID_KEY_BASE64 }}" > $RUNNER_TEMP/keystore.jks
          echo "storeFile=$RUNNER_TEMP/keystore.jks" >> keystore.properties

      - name: setup Android signing build (override)
        if: matrix.mobile == 'android'
        run: |
          mv build/build.gradle.kts src-tauri/gen/android/app/build.gradle.kts

      - name: Tauri Project
        uses: tauri-apps/tauri-action@dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_PRIVATE_KEY_PASSWORD }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: "${{ github.ref_name }}"
          releaseAssetNamePattern: '[name]_[version]_[platform]_[arch][_setup][ext]'
          args: ${{ matrix.args }}
          retryAttempts: 1
          uploadPlainBinary: true
          uploadWorkflowArtifacts: true
          mobile: ${{ matrix.mobile }}
